Dockerfile
api/api.go
scaler/scaler.go

Add graceful shutdown of API and scaler

---

Makefile

Use vendor dir for golint

---

.github/workflows/main.yml
Makefile

Deploy binary and license with release

---

config/config.go
main.go
scaler/metric.go

Use namespace when managing pods

---

.github/workflows/main.yml
Makefile
config/config.go
config/config_test.go
example/python/README.md
example/python/cpa.yaml
go.mod
go.sum
main.go

Unit tests for config required restructuring to support better dependency
injection.
Add test action to makefile.
Add test step to CI and tidy up the CI.
Resolves #3. 
Resolves #31.
Resolves #35.

Add config unit tests, use lowercase env var names

---

CHANGELOG.md
config/config.go
config/config_test.go
example/python/cpa.yaml
main.go
models/evaluation_test.go
models/metric_test.go
models/models_test.go
scaler/evaluate.go
scaler/metric.go
scaler/scaler.go
shell/shell.go

Add shell timeout, change config env var loading

---

scaler/evaluate.go
scaler/metric.go
shell/shell.go
shell/shell_test.go

Add shell package unit tests

---

api/api.go
main.go
scaler/evaluate.go
scaler/metric.go
scaler/scaler.go
shell/shell.go
shell/shell_test.go

Restructure shell for better dependency injection

---

CHANGELOG.md
api/api.go
config/config.go
config/config_test.go
example/python/cpa.yaml
main.go
models/metric.go
models/metric_test.go
models/resource_metrics.go
scaler/evaluate.go
scaler/metric.go
scaler/scaler.go
shell/shell.go
shell/shell_test.go

Replace selector with scaletargetref

---

.github/workflows/main.yml
Makefile
README.md
config/config_test.go
cpatest/cpatest.go
evaluate/evaluate_test.go
metric/metric_test.go
models/metric_test.go
models/models_test.go
shell/shell_test.go

Add unit tests for metric gathering

---

shell/shell_test.go

Tidy shell tests

---

api/api.go
api/api_test.go
autoscaler/autoscaler.go
main.go

Add API unit tests

---

CHANGELOG.md
api/api_test.go
cmd/custom-pod-autoscaler/main.go
config/config.go
config/config_test.go
evaluate/evaluate.go
evaluate/evaluate_test.go
scaler/scaler.go
scaler/scaler_test.go

Add min/max replicas and allow disable scaling

---

CHANGELOG.md
api/api.go
api/api_test.go
evaluate/evaluate.go
example/scale-on-tweet/evaluate.py
example/simple-pod-metrics-python/evaluate.py
metric/metric.go
scaler/scaler.go

Add run type to resource metrics

---

CHANGELOG.md
cmd/custom-pod-autoscaler/main.go
config/config.go
config/config_test.go

Add startTime configuration option

---

CHANGELOG.md
config/config.go
config/config_test.go
docs/reference/configuration.md
docs/user-guide/getting-started.md
docs/user-guide/methods.md
docs/user-guide/metric-gathering.md
evaluate/evaluate_test.go
example/python-custom-autoscaler/config.yaml
example/scale-on-tweet/config.yaml
example/simple-pod-metrics-python/app/deployment.yaml
example/simple-pod-metrics-python/config.yaml
example/simple-pod-metrics-python/cpa.yaml
execute/shell/shell.go
execute/shell/shell_test.go

Add configurable entrypoint for shell method

---

CHANGELOG.md
cmd/custom-pod-autoscaler/main.go
config/config.go
config/config_test.go
docs/reference/configuration.md
docs/user-guide/rest-api.md
example/simple-pod-metrics-golang/Dockerfile
example/simple-pod-metrics-python/Dockerfile

Resolves #87 
Can enable/disable API.
Can use HTTPS, providing cert and key.

Add extra configuration to API, including HTTPS

---

.gitignore
CHANGELOG.md
README.md
api/v1/api_test.go
docs/index.md
docs/reference/configuration.md
docs/reference/rest-api/v1.md
docs/user-guide/evaluating.md
docs/user-guide/getting-started.md
evaluate/evaluate.go
evaluate/evaluate_test.go
example/post-scale-hook/evaluate.py
example/python-custom-autoscaler/cpa.yaml
example/python-custom-autoscaler/evaluate.py
example/scale-on-tweet/cpa.yaml
example/scale-on-tweet/evaluate.py
example/simple-pod-metrics-golang/Dockerfile
example/simple-pod-metrics-golang/Makefile
example/simple-pod-metrics-golang/README.md
example/simple-pod-metrics-golang/go.mod
example/simple-pod-metrics-golang/main.go
example/simple-pod-metrics-python/README.md
example/simple-pod-metrics-python/evaluate.py
metric/metric.go
scale/scale.go

Consistent naming convention

---

CHANGELOG.md
api/v1/api.go
api/v1/api_test.go
autoscaler/autoscaler.go
autoscaler/autoscaler_test.go
config/config_test.go
docs/reference/configuration.md
docs/reference/rest-api/v1.md
docs/user-guide/evaluating.md
docs/user-guide/getting-started.md
docs/user-guide/metric-gathering.md
docs/user-guide/run-types.md
evaluate/evaluate.go
evaluate/evaluate_test.go
example/post-scale-hook/evaluate.py
example/post-scale-hook/metric.py
example/python-custom-autoscaler/evaluate.py
example/python-custom-autoscaler/metric.py
example/scale-on-tweet/evaluate.py
example/simple-pod-metrics-golang/main.go
example/simple-pod-metrics-python/README.md
example/simple-pod-metrics-python/evaluate.py
example/simple-pod-metrics-python/metric.py
fake/scaler.go
fake/scaler_test.go
metric/metric.go
metric/metric_test.go
mkdocs.yml
scale/scale.go
scale/scale_test.go

Metric gathering hooks dry run

---

CHANGELOG.md
README.md
docs/reference/configuration.md
docs/user-guide/scaling-to-and-from-zero.md
example/zero-scaler/Dockerfile
example/zero-scaler/README.md
example/zero-scaler/config.yaml
example/zero-scaler/cpa.yaml
example/zero-scaler/deployment.yaml
example/zero-scaler/evaluate.py
example/zero-scaler/metric.py
mkdocs.yml
scale/scale.go
scale/scale_test.go

Add scale to and from zero

---

.github/workflows/main.yml
CHANGELOG.md
Makefile
cmd/custom-pod-autoscaler/main.go
config/config.go
config/config_test.go
docs/reference/configuration.md
docs/user-guide/methods.md
example/http-request/Dockerfile
example/http-request/README.md
example/http-request/config.yaml
example/http-request/cpa.yaml
example/http-request/deployment.yaml
example/http-request/evaluate.py
execute/http/http.go
execute/http/http_test.go
execute/shell/shell.go
execute/shell/shell_test.go
go.mod
resourceclient/resourceclient_test.go

Add HTTP method, add nil pointer check to shell

---

.github/workflows/main.yml
CHANGELOG.md
Dockerfile
Makefile
README.md
docs/reference/docker-images.md
example/custom-docker-image/Dockerfile
example/custom-docker-image/README.md
example/custom-docker-image/config.yaml
example/custom-docker-image/cpa.yaml
example/custom-docker-image/deployment.yaml
example/custom-docker-image/evaluate.py
example/custom-docker-image/metric.py
example/python-custom-autoscaler/README.md
mkdocs.yml

Add new Python images

---

example/custom-docker-image/cpa.yaml
example/downscale-stabilization/evaluate.py
example/flask-metric/deployment.yaml
example/http-request/cpa.yaml
example/post-scale-hook/cpa.yaml
example/python-custom-autoscaler/cpa.yaml
example/scale-on-tweet/cpa.yaml
example/simple-pod-metrics-golang/cpa.yaml
example/simple-pod-metrics-python/cpa.yaml
example/simple-pod-metrics-python/evaluate.py

Fix bug in pod metrics example, update pull policy

---

CHANGELOG.md
Makefile
docs/user-guide/migrating-v1-to-v2.md
main.go

Add output CPA version to log on startup

---

CHANGELOG.md
internal/evaluatecalc/evaluatecalc.go
internal/evaluatecalc/evaluatecalc_test.go

Improve error logs around evaluation JSON parsing

---

.github/workflows/main.yml
CHANGELOG.md
Dockerfile
Makefile
example/simple-pod-metrics-java/.gitattributes
example/simple-pod-metrics-java/.gitignore
example/simple-pod-metrics-java/Dockerfile
example/simple-pod-metrics-java/README.md
example/simple-pod-metrics-java/build.gradle
example/simple-pod-metrics-java/config.yaml
example/simple-pod-metrics-java/cpa.yaml
example/simple-pod-metrics-java/settings.gradle
example/simple-pod-metrics-java/src/main/java/simple/pod/metrics/java/EvaluatorAndMetricGatherer.java

Add Java example

---

CHANGELOG.md
internal/autoscaler/autoscaler.go
internal/autoscaler/autoscaler_test.go
internal/confload/confload.go
internal/confload/confload_test.go
internal/evaluatecalc/evaluatecalc.go
internal/evaluatecalc/evaluatecalc_test.go
internal/execute/execute.go
internal/execute/execute_test.go
internal/execute/http/http.go
internal/execute/http/http_test.go
internal/execute/shell/shell.go
internal/execute/shell/shell_test.go
internal/k8smetricget/externalget/externalget.go
internal/k8smetricget/k8smetricget.go
internal/k8smetricget/k8smetricget_test.go
internal/k8smetricget/objectget/objectget.go
internal/k8smetricget/objectget/objectget_test.go
internal/k8smetricget/podsget/pods.go
internal/k8smetricget/podutil/podutil.go
internal/k8smetricget/resourceget/resourceget.go
internal/metricget/metricget.go
internal/metricget/metricget_test.go
internal/scaling/scaling.go
internal/scaling/scaling_test.go
main.go

Add context and wrapping to errors

---

CHANGELOG.md
CONTRIBUTING.md
Dockerfile
example/k8s-metrics-cpu-match-expressions/Dockerfile
example/k8s-metrics-cpu-match-expressions/README.md
example/k8s-metrics-cpu-match-expressions/config.yaml
example/k8s-metrics-cpu-match-expressions/cpa.yaml
example/k8s-metrics-cpu-match-expressions/deployment.yaml
example/k8s-metrics-cpu-match-expressions/evaluate.py
example/k8s-metrics-cpu-match-expressions/metric.py
internal/k8smetricget/k8smetricget.go
internal/k8smetricget/k8smetricget_test.go

Fix K8s metrics using wrong label selector

---

CHANGELOG.md
config/execute.go
docs/user-guide/methods.md
internal/execute/http/http.go
internal/execute/http/http_test.go
main.go

Add support for mutual TLS and client certs

---

docs/user-guide/pausing-and-unpausing-scaling.md
mkdocs.yml

See jthomperoo/custom-pod-autoscaler-operator#106.

Add pausing docs

---

.github/workflows/main.yml
.gitignore
CHANGELOG.md
CONTRIBUTING.md
Dockerfile
Makefile
docs/reference/docker-images.md
example/custom-docker-image/Dockerfile

Add additional binaries and docker targets
